apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-docker
  labels:
    app: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: node-docker
        image: node-docker
        imagePullPolicy: Never
        ports:
        - containerPort: 3000