apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-docker-deployment
  labels:
    app: nodeapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: node-docker-server
        image: bishaljavarnd/node-docker:node-docker
        ports:
        - containerPort: 3000


---

apiVersion: apps/v1
kind: Service
metadata:
  name: node-docker-service
spec:
  selector:
    app: nodeapp
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110